version: 2

models:
  - name: dim_listings_cleansed
    description: "This model contains the cleaned data from the listings table."
    columns:
      - name: listing_id
        description: "The unique identifier for the listing."
        tests:
          - not_null
          - unique
      - name: host_id
        description: "The unique identifier for the host."
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id
      - name: room_type
        description: "The type of room (e.g., private room, entire home/apt, etc.)."
        tests:
          - accepted_values:
              values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']
      - name: minimum_nights
        description: "The minimum number of nights required for the listing."
        tests:
          - positive_values
     