version: 2

models:
  - name: dim_listings_cleansed
    description: "This model contains the cleaned data from the listings table."
    columns:
      - name: listing_id
        description: "The unique identifier for the listing."
        tests:
          - not_null
          - unique
      - name: host_id
        description: "The unique identifier for the host."
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id
      - name: room_type
        description: "The type of room (e.g., private room, entire home/apt, etc.)."
        tests:
          - accepted_values:
              values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']
      - name: minimum_nights
        description: "The minimum number of nights required for the listing."
        tests:
          - positive_values
  - name: dim_listings_w_hosts
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb','listings')
    columns:
      - name: price
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 50
              max_value: 500
          - dbt_expectations.expect_column_max_to_be_between:
              max_value: 5000
              config:
                severity: warn
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: INT